services:
  rfid-reader-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rfid-reader-service
    restart: unless-stopped

    # Environment variables
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO

    # Port mappings
    ports:
      - '8080:8080' # Monitoring/health check port

    # Device mappings for Raspberry Pi hardware access
    devices:
      - '/dev/i2c-1:/dev/i2c-1' # I2C for LCD
      - '/dev/spidev0.0:/dev/spidev0.0' # SPI for RFID reader
      - '/dev/spidev0.1:/dev/spidev0.1'
      - '/dev/gpiomem:/dev/gpiomem' # GPIO access

    # Privileged mode for GPIO access (alternative to device mapping)
    privileged: true
    
    # Security options to handle networking issues
    security_opt:
      - no-new-privileges:true

    # Volume mappings
    volumes:
      - ./logs:/app/logs # Application logs
      - /sys:/sys:ro # System files (read-only)

    # Network configuration
    network_mode: "bridge"

    # Health check
    healthcheck:
      test: ['CMD', 'python', '-c', 'import sys; sys.exit(0)']
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

# Volumes for persistent data
volumes:
  logs:
    driver: local
  audio_data:
    driver: local
