# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import audio_service_pb2 as audio__service__pb2


class AudioServiceStub(object):
    """Audio processing service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartAudioProcessing = channel.unary_unary(
                '/audio_service.AudioService/StartAudioProcessing',
                request_serializer=audio__service__pb2.AudioRequest.SerializeToString,
                response_deserializer=audio__service__pb2.AudioResponse.FromString,
                )
        self.GetProcessingStatus = channel.unary_unary(
                '/audio_service.AudioService/GetProcessingStatus',
                request_serializer=audio__service__pb2.StatusRequest.SerializeToString,
                response_deserializer=audio__service__pb2.StatusResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/audio_service.AudioService/HealthCheck',
                request_serializer=audio__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=audio__service__pb2.HealthCheckResponse.FromString,
                )


class AudioServiceServicer(object):
    """Audio processing service
    """

    def StartAudioProcessing(self, request, context):
        """Start audio recording and processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessingStatus(self, request, context):
        """Get the status of audio processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartAudioProcessing': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAudioProcessing,
                    request_deserializer=audio__service__pb2.AudioRequest.FromString,
                    response_serializer=audio__service__pb2.AudioResponse.SerializeToString,
            ),
            'GetProcessingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessingStatus,
                    request_deserializer=audio__service__pb2.StatusRequest.FromString,
                    response_serializer=audio__service__pb2.StatusResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=audio__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=audio__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audio_service.AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AudioService(object):
    """Audio processing service
    """

    @staticmethod
    def StartAudioProcessing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/audio_service.AudioService/StartAudioProcessing',
            audio__service__pb2.AudioRequest.SerializeToString,
            audio__service__pb2.AudioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProcessingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/audio_service.AudioService/GetProcessingStatus',
            audio__service__pb2.StatusRequest.SerializeToString,
            audio__service__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/audio_service.AudioService/HealthCheck',
            audio__service__pb2.HealthCheckRequest.SerializeToString,
            audio__service__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
