# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61udio_service.proto\x12\raudio_service\"U\n\x0c\x41udioRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x1a\n\x12recording_duration\x18\x02 \x01(\x05\x12\x15\n\routput_format\x18\x03 \x01(\t\"\xb2\x01\n\rAudioResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x17\n\x0fpredicted_class\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x15\n\rerror_message\x18\x05 \x01(\t\x12\x38\n\x0ftop_predictions\x18\x06 \x03(\x0b\x32\x1f.audio_service.ClassProbability\";\n\x10\x43lassProbability\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\"#\n\rStatusRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"O\n\x0eStatusResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x19\n\x11\x63urrent_operation\x18\x03 \x01(\t\"\x14\n\x12HealthCheckRequest\"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8b\x02\n\x0c\x41udioService\x12Q\n\x14StartAudioProcessing\x12\x1b.audio_service.AudioRequest\x1a\x1c.audio_service.AudioResponse\x12R\n\x13GetProcessingStatus\x12\x1c.audio_service.StatusRequest\x1a\x1d.audio_service.StatusResponse\x12T\n\x0bHealthCheck\x12!.audio_service.HealthCheckRequest\x1a\".audio_service.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOREQUEST']._serialized_start=38
  _globals['_AUDIOREQUEST']._serialized_end=123
  _globals['_AUDIORESPONSE']._serialized_start=126
  _globals['_AUDIORESPONSE']._serialized_end=304
  _globals['_CLASSPROBABILITY']._serialized_start=306
  _globals['_CLASSPROBABILITY']._serialized_end=365
  _globals['_STATUSREQUEST']._serialized_start=367
  _globals['_STATUSREQUEST']._serialized_end=402
  _globals['_STATUSRESPONSE']._serialized_start=404
  _globals['_STATUSRESPONSE']._serialized_end=483
  _globals['_HEALTHCHECKREQUEST']._serialized_start=485
  _globals['_HEALTHCHECKREQUEST']._serialized_end=505
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=507
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=561
  _globals['_AUDIOSERVICE']._serialized_start=564
  _globals['_AUDIOSERVICE']._serialized_end=831
# @@protoc_insertion_point(module_scope)
